image: registry.gitlab.com/maketechnology/equo/docker/gradle:adoptopenjdk8-alpine

stages:
  - build
  - release

variables:
  GRADLE_USER_HOME: $CI_PROJECT_DIR/.gradle-home
  gradle_opt: "--build-cache --no-daemon"

# HOME is to cwd so bnd will download to ~/.bnd and ~/.m2 with ~=HOME
cache:
  key: "gradle"
  paths:
    - .gradle-home/
    - .m2/
    - .bnd/

before_script:
  - export HOME=$CI_PROJECT_DIR

.all:
  artifacts:
    paths:
      - cnf/testbuild.bnd
      - cnf/testbundle.bnd
      - cnf/release
      - cnf/cache
      - cnf/build
      - build
      - build-cache
    expire_in: 12w

build:
  extends: .all
  stage: build
  script:
    - gradle $gradle_opt assemble

release:
  extends: .all
  stage: release
  script:
    - gradle $gradle_opt release
    - gradle $gradle_opt publish
  only:
    - master